### ISSUE TITLE
只有共享文件夹，然后没有服务端逻辑 通过客户端可以实现能处理并发的怎删改查吗

### ISSUE THREAD

**Issue by ToddGitHub** [AiursoftWeb/AiurVersionControl#29]
只有共享文件夹，然后没有服务端逻辑 通过客户端可以实现能处理并发的怎删改查吗

**Comment by Anduin2017** [comment]
As far as I know, you are trying to implement a shared file storage, using version controled CRUD, is that right?

No. You can't do that without a server. While this is designed as a distributed system. There also need some place as an `origin` like Git.

By the way, as for the current project progress, we are still working on the code-side collection level CRUD. As for file system monitoring, we are still planing and currently not implemented.

PR is welcome.

**Comment by ToddGitHub** [comment]
首先，感谢您的这么快就回复，目前情况是，我在使用另一个团队提供的服务端，我相当于前端，服务端只提供了一个通过key值进行修改内容的接口（可以自定义多个key值），我理解就相当于共享文件夹，但是我有些可能并发的数据要过接口存起来 ，不处理的话，这样就会造成可能用户的操作记录会丢失。我看到您的项目后，在想能不能想版本控制一样 通过多个辅助k-v 来让每次拉取信息的前端来处理之前的合并逻辑 并推送到最新的主文件上

**Comment by Anduin2017** [comment]
Ah. Since you are working on an existing project, this repo might not be suitable for you to reference directly.

While you can learn some design logic from it. Of course I believe that helps!

As for more details, you can just simply read the code and run the unit tests. So you can easily understand how we achieved offline data save and push\pull.

**Comment by ToddGitHub** [comment]
好的，谢谢您啊

**Comment by Anduin2017** [comment]
Anytime ☺!
